FROM node:18-bullseye-slim

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && corepack prepare pnpm@latest --activate && pnpm install

COPY . .

CMD ["npx", "nodemon", "src/index.js"]

